apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1
  name: app1
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: 'http'
  selector:
    app: app1
  type: NodePort